---
title: "STAT796_HW1"
author: "Colleen Brents"
date: "January 23, 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
```

```{r import data}
url <- paste0("https://raw.githubusercontent.com/cbrents/stat796logreg/master/ICU_raw.txt")
icu_raw<-read_table2(url)
```
```{r rename and recode}
icu<- icu_raw %>% 
    transmute(id=ID,
              died=STA,
              age=AGE,
              female=GENDER,
              race=factor(RACE, 
                          levels=1:3,
                          labels=c("white", "black", "other")),
              service=factor(SER,
                             levels=0:1,
                             labels=c("medical", "surgical")),
              cancer=CAN,
              renal=CRN,
              infect=INF,
              cpr=CPR,
              sbp=SYS,
              hr=HRA,
              prv_admit=PRE,
              type=factor(TYP,
                          levels=0:1,
                          labels=c("elective", "emergency")),
              fracture=FRA,
              po2_g60=PO2,
              '1-PO2'= po2_g60,
              pco2_g45=PCO,
              bicarb_g18=BIC,
              '1 - BIC' = bicarb_g18,
              creat_g2=CRE,
              conscious=factor(LOC,
                levels=0:2,
                labels=c("no_coma_or_stupor", "stupor", "coma")))
```

```{r summary stats}
blrb<- icu %>% 
  summarize(mean_age = mean(age),
            max_age = max(age),
            min_age = min(age),
            sd_age =sd(age)) 

table (icu$service)
table(icu$type)
count(icu, race, female)
table(icu$race, icu$female)
count(icu, conscious)
table(icu$conscious)
```
```{r summary stats for cohort by vital status}
vitals1 <- icu %>% 
  group_by(died) %>% 
  summarize(mean_age = mean(age),
            max_age = max(age),
            min_age = min(age),
            sd_age =sd(age))  # died == 0  alive == 1
vitals2 <- icu %>% 
  group_by(type, race, female, conscious) %>% 
  tally %>%   #counts of subjects with each service type, procedure type, race, sex, consciousness %>% 
group_by(died)

vital_dead <- icu  %>% 
  filter(died ==0) %>% 
  group_by(type, race, female, conscious) %>% 
  tally  #counts of subjects with each service type, procedure type, race, sex, consciousness 
vital_dead$status <- "dead"
 
vital_alive <- icu  %>% 
  filter(died ==1) %>% 
  group_by(type, race, female, conscious) %>% 
  tally  #counts of subjects with each service type, procedure type, race, sex, consciousness 
vital_alive$status <- "alive"

#ask if want summary stats for a:d combined or in their own lines 
```

```{r graphical summaries of data}

ggplot(icu) +
  theme_bw() +
  geom_point(aes(x=sbp, 
                 y=age, 
                 color= as.factor(died), 
                 shape=as.factor(died))) +
  xlab("systolic blood pressure") +
  ylab("age (years)") +
  ggtitle("5a") +
  scale_color_discrete(name="Died or not") +
  scale_shape_discrete(name="Died or not")  #having the same text for legens combines them 

```

```{r}
ggplot(icu) +
  theme_bw() +
  geom_boxplot(aes(group = as.factor(died), x=as.factor(died), y= hr)) +
  xlab("vital status at discharge") +
  ylab("heart rate (bpm)") +
  ggtitle("5b") +
  scale_x_discrete(labels = c("alive", "dead"))
```


```{r}
ggplot(icu) +
  theme_bw() +
  geom_histogram(aes(x=age)) +
  xlab("age(years)") +
  ylab("count") +
  ggtitle("5c") 

```

```{r}
ggplot(icu, aes(x=hr, group=died)) +
  theme_bw() +
  geom_density(stat="density")

ggplot(icu, aes(group =as.factor(died), x=hr)) +
  theme_bw() +
  geom_density(x=hr)
  geom_line(aes(group=died, x=hr))
  
  
  ggplot(icu, aes()) + theme_bw() + 
  geom_line(aes(x=age), stat="density")
  
  xlab("Age (years)") + ylab("Density"
```


